### ISSUE TITLE
[FeatureRequest] Rotate Images

### ISSUE THREAD

**Issue by JFViola** [weimin-liu/msiAlign#2]
Hi, maybe it would be useful to be able to also rotate the images, besides resizing etc.

**Comment by weimin-liu** [comment]
The old version has the ability to rotate, but I intentionally deleted the function since it requires more matrix transformation and needs more maintenance. Is there any benefits of rotating images inside the app over rotating the images before being imported to the app?

**Comment by JFViola** [comment]
Not so much, besides sometimes you only realize it when the file is loaded. Minor Inconvenience.
